print("Đây là công cụ tính điểm trung bình môn(không tính hệ số)")
print("Nhập vào điểm toán của bạn")
m=float(input())
print("Nhập vào điểm vật lý của bạn")
p=float(input())
print("Nhập vào điểm hóa học của bạn")
c=float(input())
print("Nhập vào điểm sinh học của bạn")
b=float(input())
aver=(m+p+c+b)/4
print("Điểm trung bình 4 môn của bạn là: ",aver)